I think... if it can running on the JVM and maybe it is java...
dd-center/DDatJava pull request #2
Opened 2022-06-13 10:03 UTC by TheSmileCat

加了点新功能，例如命令行、调用api.vtbs.moe获取VTB信息、调用api.bilibili.com获取UP主详情信息、自动生成注释的Yaml配置文件什么的
程序启动参数暂时被去掉了。
vtbs.moe似乎没有提供获取直播间封面图像的功能，
发布到maven后，其他项目可以将其加入类路径，使用 
```kotlin
moe.vtbs.DDCore.getSpaceInfoAsync(12345678).liveRoom.getCoverImageAsync()
```
或
```java
moe.vtbs.DDCore.getSpaceInfo(12345678).liveRoom.getCoverImage()
```
可以直接拿到直播间封面的BufferedImage等。
程序入口点在Bootstrap.kt/DDCore.kt
Vtbs网站的分布服务移动到了moe.vtbs.service.impl.CenterServerDistributionService中
使用OKHttp

2022-06-13 17:17 UTC, ssysm requested changes
好大一个PR，感谢refact

还有一个小问题，那个 `lib/compileOnly/android.jar` 可以从maven拉吗还是说必须存lib里

2022-06-13 17:17 UTC, ssysm commented on src/main/java/moe/vtbs/job/JobProcessor.java
> +import moe.vtbs.DDatJava;
import了多余的一个？

2022-06-13 17:17 UTC, ssysm commented on src/main/java/moe/vtbs/job/JobSocket.java
> +import moe.vtbs.DDatJava;
同上

2022-06-13 17:17 UTC, ssysm commented on src/main/java/moe/vtbs/job/JobWorker.java
> +import moe.vtbs.DDatJava;
同同上

2022-06-13 17:17 UTC, ssysm commented on build.gradle.kts
> +version = "1.1.0.0"
可以直接bump到2.0.0

2022-06-13 17:17 UTC, ssysm commented on src/test/kotlin/moe/vtbs/BootstrapTest.kt
> +    @Deprecated("有没有一种可能……Scanner不能与JUnit一同使用？")
that's a good one! 🤣

2022-06-13 17:17 UTC, ssysm commented on src/test/kotlin/moe/vtbs/DDCoreTest.kt
> +        //logger.info("开始测试")
没其他作用的话可以删了

2022-06-13 17:17 UTC, ssysm commented
整体看起来没问题，版本最好使用SemVer格式, 这个PR有很多breaking change可以直接上 2.0.0。

这个项目还没license, 看你文件头的版权声明是GPLv3那直接选GPLv3了。

后面我加一个CI估计就OK了

2022-06-13 17:24 UTC, lolosiax commented on src/main/java/moe/vtbs/job/JobProcessor.java
> +import moe.vtbs.DDatJava;
哦哦，import 重复了那是 IDEA 的 bug，移动软件包每次都出问题，我改了软件包之后全局替换掉了旧的包名（为了修复IDEA造成的指向旧软件包的BUG），所以发生了了重复
我没太注意过import的问题，IDEA默认是吧这一片地方折叠起来的，我以后会注意下

2022-06-13 17:28 UTC, lolosiax commented on src/test/kotlin/moe/vtbs/DDCoreTest.kt
> +        //logger.info("开始测试")
这些内容是测试用的，如果有影响的话，我之后改一下 .gitignore ，把测试部分从git中排除出去

2022-06-13 17:35 UTC, TheSmileCat commented
那个 `lib/compileOnly/android.jar` 是从Andorid SDK中抽出来的，一个Jar有 20Mbytes，太大了。
而且我没在 `mvnrepo...` 网站上找到android.jar什么的……

2022-06-13 17:39 UTC, TheSmileCat commented
如果有一个repo服务器就好了，那个 README.md 写的使用此项目的方法太麻烦了
（看dd-center大多数项目都是JS写的，应该是有Node.js什么的repo服务器的，但java这边……）

2022-06-15 16:54 UTC, ssysm approved these changes

2022-06-15 16:54 UTC, merged

2022-06-15 16:55 UTC, ssysm commented
抱歉周末太忙忘看了, merged.